name: traefik-ping
services:
  traefik:
    image: traefik:v3.7.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "636:636"
    env_file: 
    - .env  
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf_api_token # Mount CF API Token for cloudflare
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}  # Read from .env file
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json   # populated with generate wildcard cert
      - ./traefik/logs:/var/log/traefik   # Logging output for troubleshooting
    secrets:
      - cf_api_token  # secret created from ./traefik/cf_api_token.txt file & auto mounted to container /run/secrets

    labels:
      - "traefik.tls.stores.default.defaultgeneratedcert.resolver=cloudflare"      # Setup default cert to be Let's Encrypt wildcard - for use when terminating PD LDAPS connections
      - "traefik.tls.stores.default.defaultgeneratedcert.domain.main=${DNS_DOMAIN}"
      - "traefik.tls.stores.default.defaultgeneratedcert.domain.sans=*.${DNS_DOMAIN}"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"  # Enable traefik dashboard - with redirect to https
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DNS_DOMAIN}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}" # setup basic auth for Traefik Dashboard
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"  
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"    # Force headers for PA and PF to be https - required for proper operation of PA and PF
      - "traefik.http.middlewares.secure-proto.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DNS_DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"    # Link Basic auth to Traefik Dashboard
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"  # Key values to getting Let's encrypt wild card cert generated and used for Traefik and LDAPS termination
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${DNS_DOMAIN}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${DNS_DOMAIN}"
      - "traefik.http.routers.traefik-secure.service=api@internal"


  pingdirectory:
    image: pingidentity/pingdirectory
    hostname: pingdirectory
    container_name: pingdirectory
    env_file:
      - ./ping/devops-crds.env
      - .env
    labels:  
      - "traefik.enable=true" # Enable Traefik routing for this service - with HTTPS and LDAPS Termination to PD LDAP 1389 internally
      - "traefik.http.routers.pingdirectory.entrypoints=https"
      - "traefik.http.routers.pingdirectory.rule=Host(`pd.${DNS_DOMAIN}`)"
      - "traefik.http.routers.pingdirectory.tls=true"
      - "traefik.http.services.pingdirectory.loadbalancer.server.port=1443"
      - "traefik.http.services.pingdirectory.loadbalancer.server.scheme=https" 
      - "traefik.tcp.routers.ldaps-srv.entrypoints=ldaps"
      - "traefik.tcp.routers.ldaps-srv.tls=true"
      - "traefik.tcp.routers.ldaps-srv.rule=HostSNI(`pd.${DNS_DOMAIN}`)"
      - "traefik.tcp.routers.ldaps-srv.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.ldaps-srv.service=ldaps-srv"
      - "traefik.tcp.services.ldaps-srv.loadbalancer.server.port=1389"
    environment:
      - MAKELDIF_USERS=1000  # create 1000 sample users in PD for testing - can be removed if not needed
    volumes:
      - ./profiles/pingdirectory:/opt/in:ro  # Mount the profile for PD to be used for initial configuration
      - pingdirectory-out:/opt/out    # Mount the output directory for PD to be used for persisting data and configuration
    networks:
      - proxy


  pingdataconsole:   # PD Console GUI
    image: pingidentity/pingdataconsole
    hostname: pingdataconsole
    container_name: pingdataconsole
    env_file:
      - ./ping/devops-crds.env
      - .env
    labels:  
      - "traefik.enable=true"  # Expose pdc via Trafik - via HTTPS Termination
      - "traefik.http.routers.pingdataconsole.entrypoints=https"
      - "traefik.http.routers.pingdataconsole.rule=Host(`pdc.${DNS_DOMAIN}`)"
      - "traefik.http.routers.pingdataconsole.tls=true"
      - "traefik.http.services.pingdataconsole.loadbalancer.server.port=1443"
      - "traefik.http.services.pingdataconsole.loadbalancer.server.scheme=https"  
    volumes:
      - ./profiles/pingdataconsole:/opt/in:ro  # Mount the profile for PDC so that LDAP Server & Creds pre-populated  
    networks:
      - proxy

  pingaccess:
    image: pingidentity/pingaccess
    hostname: pingaccess
    container_name: pingaccess
    depends_on:  # Have pingaccess standalone wait for pingfederate-admin to be up and running before starting
      - pingfederate-admin
    command: wait-for pingfederate-admin:9999 -t 600 -- entrypoint.sh start-server
    env_file:
      - ./ping/devops-crds.env
      - .env
    environment:
      - PA_LOG_LEVEL=DEBUG
      - OPERATIONAL_MODE=STANDALONE  
      - PF_ENGINE_PRIVATE_HOSTNAME=pingfederate  # Overwrite the default value for PF_ENGINE_PRIVATE_HOSTNAME to point to the pingfederate container name - required for proper operation of PA and PF

    labels:  
      - "traefik.enable=true"  # Setup Traefik for PA - with both Admin Console and sample application engine exposed via HTTPS Termination
      - "traefik.http.routers.pa-admin.entrypoints=https"
      - "traefik.http.routers.pa-admin.rule=Host(`pa-admin.${DNS_DOMAIN}`)"
      - "traefik.http.routers.pa-admin.tls=true"
      - "traefik.http.routers.pa-admin.service=pa-admin"
      - "traefik.http.services.pa-admin.loadbalancer.server.port=9000"
      - "traefik.http.services.pa-admin.loadbalancer.server.scheme=https"  
      - "traefik.http.routers.pa-engine.entrypoints=https"
      - "traefik.http.routers.pa-engine.rule=Host(`pa.${DNS_DOMAIN}`)"
      - "traefik.http.routers.pa-engine.tls=true"
      - "traefik.http.routers.pa-engine.service=pa-engine"
      - "traefik.http.services.pa-engine.loadbalancer.server.port=3000"
      - "traefik.http.services.pa-engine.loadbalancer.server.scheme=https" 
      - "traefik.http.routers.myapp.entrypoints=https" # Setup for generic sample application engine exposed via HTTPS Termination - for testing and validation of Traefik routing
      - "traefik.http.routers.myapp.rule=Host(`${APP_PUBLIC_HOSTNAME}`)"
      - "traefik.http.routers.myapp.tls=true"
      - "traefik.http.routers.myapp.service=myapp"
      - "traefik.http.services.myapp.loadbalancer.server.port=3000"
      - "traefik.http.services.myapp.loadbalancer.server.scheme=https" 
    volumes:
      - ./profiles/pingaccess:/opt/in:ro  
      - pingaccess-admin-out:/opt/out
    networks:
      - proxy      

  pingfederate-admin:
    image: pingidentity/pingfederate
    hostname: pingfederate-admin
    container_name: pingfederate-admin
    depends_on:
      - pingdirectory
    command: wait-for pingdirectory:1389 -t 600 -- entrypoint.sh start-server
    env_file:
      - ./ping/devops-crds.env
      - .env
    environment:
      - OPERATIONAL_MODE=CLUSTERED_CONSOLE
      - CLUSTER_NAME=pf
      - DNS_QUERY_LOCATION=pingfederate-admin,pingfederate
      - DNS_RECORD_TYPE=A
      - TAIL_LOG_FILES="/opt/out/instance/log/server.log /opt/out/instance/log/init.log /opt/out/instance/log/admin.log"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pingfederate-admin.entrypoints=https"
      - "traefik.http.routers.pingfederate-admin.rule=Host(`pf-admin.${DNS_DOMAIN}`)"
      - "traefik.http.routers.pingfederate-admin.tls=true"
      - "traefik.http.services.pingfederate-admin.loadbalancer.server.port=9999"
      - "traefik.http.services.pingfederate-admin.loadbalancer.server.scheme=https"
    networks:
      - proxy
    volumes:
      - pingfederate-admin-out:/opt/out
      - ./profiles/pingfederate:/opt/in:ro

  pingfederate:
    image: pingidentity/pingfederate # ${PING_IDENTITY_DEVOPS_TAG}
    hostname: pingfederate-engine
   
    depends_on:
      - pingfederate-admin
    command: wait-for pingfederate-admin:9999 -t 600 -- entrypoint.sh start-server
    # You may need to comment this tmpfs line if you run containers on windows
    env_file:
         - ./ping/devops-crds.env
         - .env
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
    
      - OPERATIONAL_MODE=CLUSTERED_ENGINE
      - CLUSTER_NAME=pf
      - DNS_QUERY_LOCATION=pingfederate-admin,pingfederate
      - DNS_RECORD_TYPE=A
     
    labels:  
      - "traefik.enable=true"
      - "traefik.http.routers.pingfederate.entrypoints=https"
      - "traefik.http.routers.pingfederate.rule=Host(`pf.${DNS_DOMAIN}`)"
      - "traefik.http.routers.pingfederate.tls=true"
   
      - "traefik.http.services.pingfederate.loadbalancer.server.port=9031"
      - "traefik.http.services.pingfederate.loadbalancer.server.scheme=https"
    volumes:
       - ./profiles/pingfederate:/opt/in:ro
    networks:
      - proxy

  echo-server: 
        image: ealen/echo-server:0.9.2
        container_name: echo-server
        labels:  
          - "traefik.enable=true"
          - "traefik.http.routers.echo-server.entrypoints=https"
          - "traefik.http.routers.echo-server.rule=Host(`echo.${DNS_DOMAIN}`)"
          - "traefik.http.routers.echo-server.tls=true"
          - "traefik.http.services.echo-server.loadbalancer.server.port=80"
          - "traefik.http.services.echo-server.loadbalancer.server.scheme=http"
          - "traefik.http.routers.catchall.rule=Host(`*`)"
          - "traefik.http.routers.catchall.entrypoints=https"
          - "traefik.http.routers.catchall.priority=1"
          - "traefik.http.routers.catchall.tls=true"
          - "traefik.http.routers.catchall.service=echo-server"
        networks:
          - proxy      

  

volumes:
  pingfederate-admin-out:
  pingdirectory-out:
  pingaccess-admin-out:

secrets:
  cf_api_token:
    file: ./traefik/cf_api_token.txt

networks:
  proxy:
    driver: bridge
    name: proxy
